name: cicd

on: 
    pull_request: 
        branches:
            - main
            - develop
    push:
        branches:
            - main

jobs:
    unit-tests:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18, 22]
                    
        steps:
            - name: checkout
              uses: actions/checkout@v2

            - name: node
              uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node-version }}

            - name: run tests
              run: npm run test:ci

            - name: run lint tests
              run: npm run lint
                
            - name: saummary
              run: echo "Test ok"
            